# Generated by Django 5.0.7 on 2024-07-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0002_remove_pedido_plato_pedido_fecha_hora_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.cliente')),
                ('platos', models.ManyToManyField(to='gestion_pedidos.plato')),
            ],
        ),
    ]
