# Generated by Django 5.0.7 on 2024-07-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0003_remove_carroitem_usuario_carroitem_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='image',
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.CharField(default='images/platos/default.png', max_length=255),
        ),
    ]
