# Generated by Django 5.0.7 on 2024-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0004_plato_descripcion_plato_featured_alter_plato_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
