# Generated by Django 5.0.7 on 2024-07-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0004_remove_plato_image_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(default='platos/default.jpg', upload_to='platos/'),
        ),
    ]
