# Generated by Django 5.0.7 on 2024-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0005_plato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='image',
            field=models.ImageField(default='default.png', upload_to='platos/'),
        ),
    ]
