# Generated by Django 5.0.7 on 2024-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0005_alter_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.CharField(default='images/platos/default.png', max_length=255),
        ),
    ]
